//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.24 at 02:18:46 PM MSK 
//


package com.bercut.specs.dsi.tele2.tarantoolcache;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Bpmloader" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Aspxauth" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Username" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BpmSessionId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LifeTime" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "bpmloader",
    "aspxauth",
    "username",
    "bpmSessionId",
    "lifeTime"
})
@XmlRootElement(name = "insertNewTokenRequest")
public class InsertNewTokenRequest {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Bpmloader", required = true)
    protected String bpmloader;
    @XmlElement(name = "Aspxauth", required = true)
    protected String aspxauth;
    @XmlElement(name = "Username", required = true)
    protected String username;
    @XmlElement(name = "BpmSessionId", required = true)
    protected String bpmSessionId;
    @XmlElement(name = "LifeTime")
    protected int lifeTime;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the bpmloader property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBpmloader() {
        return bpmloader;
    }

    /**
     * Sets the value of the bpmloader property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBpmloader(String value) {
        this.bpmloader = value;
    }

    /**
     * Gets the value of the aspxauth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAspxauth() {
        return aspxauth;
    }

    /**
     * Sets the value of the aspxauth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAspxauth(String value) {
        this.aspxauth = value;
    }

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsername(String value) {
        this.username = value;
    }

    /**
     * Gets the value of the bpmSessionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBpmSessionId() {
        return bpmSessionId;
    }

    /**
     * Sets the value of the bpmSessionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBpmSessionId(String value) {
        this.bpmSessionId = value;
    }

    /**
     * Gets the value of the lifeTime property.
     * 
     */
    public int getLifeTime() {
        return lifeTime;
    }

    /**
     * Sets the value of the lifeTime property.
     * 
     */
    public void setLifeTime(int value) {
        this.lifeTime = value;
    }

}
